version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mediconnect-mysql
    restart: always
    environment:
      MYSQL_DATABASE: mediconnectdb
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend
    container_name: mediconnect-backend
    ports:
      - "5050:5050"
    environment:
      - DB_HOST=mysqldb
    env_file:
      - ./backend/.env
    depends_on:
      mysqldb:
        condition: service_healthy
  frontend:
    build: ./frontend
    container_name: mediconnect-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mysql_data: